# Generated by Django 3.2.4 on 2021-06-18 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_nombre', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_titulo', models.CharField(max_length=64)),
                ('producto_descripcion', models.CharField(max_length=120)),
                ('producto_precio', models.IntegerField()),
                ('producto_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_categoria', to='TIENDAVIRTUAL.categoria')),
            ],
        ),
    ]
