# Generated by Django 3.2.4 on 2021-06-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIENDAVIRTUAL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria_nombre',
            field=models.CharField(help_text='Ej.: Árbol, Arbusto, etc...', max_length=64),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
