# Generated by Django 3.2.4 on 2021-06-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIENDAVIRTUAL', '0003_producto_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='producto_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
