# Generated by Django 3.2.4 on 2021-06-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIENDAVIRTUAL', '0004_alter_producto_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nombre', models.CharField(max_length=64)),
                ('usuario_productos', models.ManyToManyField(blank=True, related_name='usuarios', to='TIENDAVIRTUAL.Producto')),
            ],
        ),
    ]
