# Generated by Django 3.2.4 on 2021-06-20 20:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TIENDAVIRTUAL', '0006_agregaralcarrito'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgregarAlCarrito',
            new_name='Carrito',
        ),
    ]
