# Generated by Django 3.2.4 on 2021-06-21 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TIENDAVIRTUAL', '0007_rename_agregaralcarrito_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='carrito_producto',
            field=models.ManyToManyField(blank=True, related_name='carrito_producto', to='TIENDAVIRTUAL.Producto'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_nombre', to=settings.AUTH_USER_MODEL),
        ),
    ]
