# Generated by Django 3.2.4 on 2021-06-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIENDAVIRTUAL', '0008_auto_20210621_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario_nombre',
            field=models.CharField(max_length=64),
        ),
    ]
