# Generated by Django 3.2.4 on 2021-06-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIENDAVIRTUAL', '0009_alter_usuario_usuario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='carrito_producto',
            field=models.ManyToManyField(to='TIENDAVIRTUAL.Producto'),
        ),
    ]
