# Generated by Django 3.2.4 on 2021-07-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIENDAVIRTUAL', '0010_alter_carrito_carrito_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='producto_descripcion',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_titulo',
            field=models.CharField(help_text='Ingrese el nombre del producto', max_length=64),
        ),
    ]
